name = "FreePoleHeom"
uuid = "1b3ed703-cc68-4823-bf01-7c2dbc0910fe"
authors = ["Malte Krug <malte.krug@proton.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
