name = "FreePoleHeom"
uuid = "1b3ed703-cc68-4823-bf01-7c2dbc0910fe"
version = "1.0.0-DEV"
authors = ["Malte Krug <malte.krug@proton.me> and contributors"]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BaryRational = "91aaffc3-5777-4842-85b7-5d3d5d6a3494"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Arpack = "0.5.4"
BaryRational = "1.1.1"
LinearAlgebra = "1.12.0"
SparseArrays = "1.12.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
